<?php
 $groups = $this->getGroups();
 $storeviews = $this->getStoreviews();
 $currentSelect = $this->getCurrentStorviews();
?>

<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td class="value">
        <select id="<?php echo $this->getElement()->getId() ?>" name="<?php echo $this->getElement()->getName() ?>"
                class="select">
            <?php foreach ($groups as $group):?>
                <optgroup label="<?php echo $group->getName()?>">
                    <?php
                        foreach ($storeviews as $storeview):
                            if($storeview->getGroupId() == $group->getId()):
                     ?>
                        <option value="<?php echo $storeview->getId()?>"
                            <?php if ($currentSelect == $storeview->getId()):?>selected="selected"<?php endif;?>>
                            <?php echo $storeview->getName()?>
                        </option>
                    <?php
                            endif;
                        endforeach;
                    ?>
            <?php endforeach;?>
        </select>
    </td>
</tr>
