<script type="text/javascript">
    //<![CDATA[
    function check() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'POST',
            onSuccess: function(transport){

                if (transport.responseText){

                    data = JSON.parse(transport.responseText);
                    console.log(data.storeview);
                    alert(data.storeview.message);
                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>